# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class XquareCli < Formula
  desc "PaaS CLI for DSM student teams"
  homepage "https://github.com/team-xquare/xquare-cli"
  version "0.5.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/team-xquare/xquare-cli/releases/download/v0.5.0/xquare_0.5.0_darwin_amd64.tar.gz"
      sha256 "6491cc3a2f27ad564342d3a03487ecc92a13e099a31fd677b0df8596d27e1f24"

      define_method(:install) do
        bin.install "xquare"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/team-xquare/xquare-cli/releases/download/v0.5.0/xquare_0.5.0_darwin_arm64.tar.gz"
      sha256 "9662831264ec6fb16281ab184e63174f10edc94b0be0d9fee0e24b941f278ba1"

      define_method(:install) do
        bin.install "xquare"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/team-xquare/xquare-cli/releases/download/v0.5.0/xquare_0.5.0_linux_amd64.tar.gz"
      sha256 "231e283370699e1aa6a9287eec7bd30c6a93829bfae59f294a3e56d1ca2df91d"
      define_method(:install) do
        bin.install "xquare"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/team-xquare/xquare-cli/releases/download/v0.5.0/xquare_0.5.0_linux_arm64.tar.gz"
      sha256 "905eaa4c7e42894f2e55ef873ee5488e54c2b491683a958fde7e458d39323ef2"
      define_method(:install) do
        bin.install "xquare"
      end
    end
  end

  test do
    system "#{bin}/xquare version"
  end
end
