# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class XquareCli < Formula
  desc "PaaS CLI for DSM student teams"
  homepage "https://github.com/team-xquare/xquare-cli"
  version "0.4.46"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/team-xquare/xquare-cli/releases/download/v0.4.46/xquare_0.4.46_darwin_amd64.tar.gz"
      sha256 "3c0350aaad857673bb58b3c5fad72a639eb48fae29c01a0dbc76da4a571f7a7d"

      define_method(:install) do
        bin.install "xquare"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/team-xquare/xquare-cli/releases/download/v0.4.46/xquare_0.4.46_darwin_arm64.tar.gz"
      sha256 "d112a44f4d47ac51df9aa15509433c1bf6d7b603da3907416f332415225b0996"

      define_method(:install) do
        bin.install "xquare"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/team-xquare/xquare-cli/releases/download/v0.4.46/xquare_0.4.46_linux_amd64.tar.gz"
      sha256 "27ba87f86fa1dae7cd8c3b3166a738e11e9298fb9e7d7ab40214574537d2032b"
      define_method(:install) do
        bin.install "xquare"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/team-xquare/xquare-cli/releases/download/v0.4.46/xquare_0.4.46_linux_arm64.tar.gz"
      sha256 "9d708b117cb6da067e33994145abc97dd2960d990f0a9c468fa13688a9ba0489"
      define_method(:install) do
        bin.install "xquare"
      end
    end
  end

  test do
    system "#{bin}/xquare version"
  end
end
