# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Xquare < Formula
  desc "PaaS CLI for DSM student teams"
  homepage "https://github.com/team-xquare/xquare-cli"
  version "0.2.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/team-xquare/xquare-cli/releases/download/v0.2.2/xquare_0.2.2_darwin_amd64.tar.gz"
      sha256 "18b771f3977964dfec0d7c8312cf8b4e7becba668183f60934a4a1b1d2aaf46b"

      define_method(:install) do
        bin.install "xquare"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/team-xquare/xquare-cli/releases/download/v0.2.2/xquare_0.2.2_darwin_arm64.tar.gz"
      sha256 "581d770a0bec2f8b46d959e84f593354db4fda2fd632dd969bdc69d217870c04"

      define_method(:install) do
        bin.install "xquare"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/team-xquare/xquare-cli/releases/download/v0.2.2/xquare_0.2.2_linux_amd64.tar.gz"
      sha256 "69d265f1778f5b14e9a8cacd228616014f86bb6b45de5d3c45d19cca3ec59aaa"
      define_method(:install) do
        bin.install "xquare"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/team-xquare/xquare-cli/releases/download/v0.2.2/xquare_0.2.2_linux_arm64.tar.gz"
      sha256 "73928d85a234bf55c2dbb08b099921ceba3e084d8ab34c752a2e7b69927ad6f3"
      define_method(:install) do
        bin.install "xquare"
      end
    end
  end

  test do
    system "#{bin}/xquare version"
  end
end
